Imports

In [2]:
import pandas as pd
import numpy as np

Basic Math

In [3]:
#basic math
4*5

20

In [8]:
np.exp(10)

np.float64(22026.465794806718)

In [12]:
sentence="first notebook"

In [15]:
sentence.upper()

'FIRST NOTEBOOK'

In [13]:
sentence.capitalize()

'First notebook'

In [1]:
import time

start=time.time()
for i in range(999999):
    if i%200000==0:
        print(i)
        print(time.time()-start)

0
0.0
200000
0.019301176071166992
400000
0.044670820236206055
600000
0.07240104675292969
800000
0.08876562118530273


In [12]:
list=[1,2,3,4,5]
arr=np.array(list)
arr

array([1, 2, 3, 4, 5])

In [13]:
arr*2+2

array([ 4,  6,  8, 10, 12])

In [24]:
arr=[[[1,2],[3,4],[5,6]]]
arr=np.array(arr)
arr

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [28]:
print(arr[0,1,0])

3


In [29]:
arr*2+3

array([[[ 5,  7],
        [ 9, 11],
        [13, 15]]])